"""
Evaluate saved UI recordings with a trained speech command model.

The expected label is parsed from filenames generated by interactive_test.py,
for example: yes_015.wav, zh_zero_006.wav.
"""

import argparse
import json
import re
import sys
import torch
import torch.nn.functional as F
import numpy as np
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from scipy.io import wavfile
from scipy import signal

sys.path.insert(0, str(Path(__file__).parent))
from model import create_model
from preprocess import (
    BILINGUAL_40_WORDS,
    Config,
    compute_mel_spectrogram,
    normalize_spectrogram,
    pad_or_truncate,
)


def parse_expected_label(path: Path) -> str:
    stem = path.stem
    match = re.match(r"^(zh_[a-z]+|[a-z]+)_\d+$", stem)
    if not match:
        raise ValueError(f"Cannot parse expected label from filename: {path.name}")
    return match.group(1)


def get_device(device: str) -> torch.device:
    if device == "auto":
        if torch.cuda.is_available():
            return torch.device("cuda")
        return torch.device("cpu")
    return torch.device(device)


def load_model(model_path: Path, device: torch.device):
    model = create_model("standard", num_classes=40)
    checkpoint = torch.load(str(model_path), map_location=device, weights_only=False)
    model.load_state_dict(checkpoint.get("model_state_dict", checkpoint))
    model.to(device)
    model.eval()
    return model


def load_wav_fast(path: Path, target_sr: int) -> np.ndarray:
    sr, audio = wavfile.read(str(path))
    if audio.ndim > 1:
        audio = audio.mean(axis=1)
    if np.issubdtype(audio.dtype, np.integer):
        max_val = np.iinfo(audio.dtype).max
        audio = audio.astype(np.float32) / max_val
    else:
        audio = audio.astype(np.float32)
    if sr != target_sr:
        gcd = np.gcd(sr, target_sr)
        audio = signal.resample_poly(audio, target_sr // gcd, sr // gcd).astype(np.float32)
    return audio


def predict(model, device: torch.device, wav_path: Path, top_k: int = 5):
    audio = load_wav_fast(wav_path, Config.SAMPLE_RATE)
    target_len = int(Config.SAMPLE_RATE * Config.AUDIO_DURATION)
    audio = pad_or_truncate(audio, target_len)
    spec = compute_mel_spectrogram(audio, sr=Config.SAMPLE_RATE, n_mels=Config.N_MELS)
    spec = normalize_spectrogram(spec, method="global")
    tensor = torch.from_numpy(spec).float().unsqueeze(0).unsqueeze(0).to(device)

    with torch.no_grad():
        probs = F.softmax(model(tensor), dim=1).squeeze(0)

    top_probs, top_indices = torch.topk(probs, k=top_k)
    return [
        (BILINGUAL_40_WORDS[int(idx)], float(prob))
        for idx, prob in zip(top_indices.cpu(), top_probs.cpu())
    ]


def evaluate_recordings(model_path: Path, recordings_dir: Path, output_dir: Path, device: str):
    torch_device = get_device(device)
    model = load_model(model_path, torch_device)

    wav_files = sorted(recordings_dir.glob("*.wav"))
    if not wav_files:
        wav_files = sorted(recordings_dir.glob("*/*.wav"))
    if not wav_files:
        raise FileNotFoundError(f"No wav files found under {recordings_dir}")

    results = []
    per_word = defaultdict(lambda: {"correct": 0, "total": 0})
    per_folder = defaultdict(lambda: {"correct": 0, "total": 0})
    totals = {
        "overall": {"correct": 0, "total": 0},
        "EN": {"correct": 0, "total": 0},
        "ZH": {"correct": 0, "total": 0},
    }

    for wav in wav_files:
        expected = parse_expected_label(wav)
        language = "ZH" if expected.startswith("zh_") else "EN"
        predictions = predict(model, torch_device, wav, top_k=5)
        predicted, confidence = predictions[0]
        correct = predicted == expected

        for bucket in ("overall", language):
            totals[bucket]["total"] += 1
            if correct:
                totals[bucket]["correct"] += 1
        per_word[expected]["total"] += 1
        per_folder[wav.parent.name]["total"] += 1
        if correct:
            per_word[expected]["correct"] += 1
            per_folder[wav.parent.name]["correct"] += 1

        results.append({
            "folder": wav.parent.name,
            "file": wav.name,
            "expected": expected,
            "predicted": predicted,
            "language": language,
            "confidence": confidence,
            "correct": correct,
            "top5": [{"word": w, "confidence": c} for w, c in predictions],
        })

    def add_acc(item):
        item = dict(item)
        item["accuracy"] = item["correct"] / item["total"] if item["total"] else 0.0
        return item

    report = {
        "timestamp": datetime.now().strftime("%Y%m%d_%H%M%S"),
        "model": str(model_path.resolve()),
        "recordings_dir": str(recordings_dir.resolve()),
        "note": "Evaluation of saved real UI recordings; expected labels are parsed from filenames.",
        "totals": {k: add_acc(v) for k, v in totals.items()},
        "per_word": {k: add_acc(v) for k, v in sorted(per_word.items())},
        "per_folder": {k: add_acc(v) for k, v in sorted(per_folder.items())},
        "details": results,
    }

    output_dir.mkdir(parents=True, exist_ok=True)
    json_path = output_dir / "recordings_eval.json"
    txt_path = output_dir / "recordings_eval.txt"
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, ensure_ascii=False)

    with open(txt_path, "w", encoding="utf-8") as f:
        f.write("Saved UI Recordings Evaluation\n")
        f.write("=" * 60 + "\n")
        f.write(f"Model: {model_path}\n")
        f.write(f"Recordings: {recordings_dir}\n\n")
        for name in ("overall", "EN", "ZH"):
            row = report["totals"][name]
            f.write(f"{name:>7}: {row['accuracy']*100:6.2f}% "
                    f"({row['correct']}/{row['total']})\n")
        f.write("\nPer folder:\n")
        for name, row in report["per_folder"].items():
            f.write(f"  {name}: {row['accuracy']*100:6.2f}% "
                    f"({row['correct']}/{row['total']})\n")
        f.write("\nMistakes:\n")
        for item in results:
            if not item["correct"]:
                f.write(f"  {item['folder']}/{item['file']}: "
                        f"{item['expected']} -> {item['predicted']} "
                        f"({item['confidence']*100:.1f}%)\n")

    print(f"[OK] Saved {json_path}")
    print(f"[OK] Saved {txt_path}")
    for name in ("overall", "EN", "ZH"):
        row = report["totals"][name]
        print(f"{name:>7}: {row['accuracy']*100:6.2f}% ({row['correct']}/{row['total']})")


def main():
    parser = argparse.ArgumentParser(description="Evaluate saved UI recordings")
    parser.add_argument("--model", required=True, type=Path)
    parser.add_argument("--recordings_dir", default=Path("../recordings"), type=Path)
    parser.add_argument("--output_dir", default=Path("../results/ui_recordings_v4"), type=Path)
    parser.add_argument("--device", default="auto")
    args = parser.parse_args()

    evaluate_recordings(args.model, args.recordings_dir, args.output_dir, args.device)


if __name__ == "__main__":
    main()
